name: Parallel Test Execution
on: [push, pull_request]
jobs:
  cypress-run-Chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Dependencies
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with: 
           cypress:run:Chrome: npm run cypress:run:Chrome

      - name: Generate Mochawesome Report
        run: npm run generate:report

      - name: Save Mochawesome Report as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: mochawesome-report
          path: cypress/reports/mochawesome     
          



  cypress-run-FireFox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Dependencies
        run: npm install
        
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with: 
           cypress:run:Firefox: npm run  cypress:run:Firefox
                 - name: Generate Mochawesome Report
        run: npm run generate:report

      - name: Save Mochawesome Report as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: mochawesome-report
          path: cypress/reports/mochawesome     
         
